workflows:
  android-workflow:
    name: Slash Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.slash"  
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew assembleDebug  # Use the wrapper
          echo "Build completed in $(pwd)"
    artifacts:
      - macroapp-environment/**/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
