workflows:
  android-workflow:
    name: Slash Android Build
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment  # Navigate to the directory with gradlew
          chmod +x gradlew       # Grant executable permissions
          ./gradlew assembleDebug # Run your build command
    artifacts:
      - macroapp-environment/**/build/outputs/**/*.apk
