workflows:
  android-workflow:
    name: Slash Android Build
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - macroapp-environment/**/build/outputs/**/*.apk
