workflows:
  android-workflow:
    name: Android Build
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment  # Adjust this to the directory containing gradlew
          chmod +x gradlew       # Grant executable permissions
          ./gradlew assembleDebug 
    artifacts:
      - macroapp-environment/**/build/outputs/**/*.apk
