workflows:
  android-workflow:
    name: Treachery Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.treachery"
    scripts:
      - name: List Gradle Tasks
        script: |
          cd macroapp-environment && gradle :app:tasks --all
          echo "Tasks listed in $(pwd)"
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
