workflows:
  android-workflow:
    name: Slash Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.slash"
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment && gradle :app:assembleDebug
          echo "Build completed in $(pwd)"
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
