workflows:
  android-workflow:
    name: Slash Android Build
    environment:
      gradle_version: 8.2  # Forces Codemagic to use Gradle 8.2
      vars:
        PACKAGE_NAME: "com.example.slash"
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment
          gradle :app:assembleDebug  # Uses Codemagic’s Gradle instead of ./gradlew
          echo "Build completed in $(pwd)"
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
