workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        # Define any environment variables here if needed (e.g., for Google Sign-In client ID)
        # - google_credentials
      vars:
        # Specify the Android package name
        PACKAGE_NAME: "com.example.macroapp"
    scripts:
      - name: Set up project path
        script: |
          cd macroapp-environment
          echo "Working directory set to $(pwd)"
      - name: Build Android App
        script: |
          # Ensure Gradle wrapper exists, or use Codemagic's default Gradle
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
    branch: main  
