workflows:
  android-workflow:
    name: Slash Android Build
    environment:
      gradle_version: 8.2
    scripts:
      - name: Build Android App
        script: |
          cd macroapp-environment
          gradle :app:assembleDebug
          echo "Build completed in $(pwd)"
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
