workflows:
  android-workflow:
    name: Treachery Android Build
    environment:
      vars:
        # Updated package name to reflect the app name "Treachery"
        PACKAGE_NAME: "com.example.treachery"
    scripts:
      - name: Set up project path
        script: |
          cd macroapp-environment
          echo "Working directory set to $(pwd)"
      - name: Build Android App
        script: |
          # Check for Gradle wrapper, fallback to Codemagic's Gradle
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi
    artifacts:
      - macroapp-environment/app/build/outputs/**/*.apk
    triggering:
      events:
        - push
        - pull_request
    branch: main
